from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
IMG_DIR = BASE_DIR / "img"

PLAYER_PATH = IMG_DIR / "player"
ENEMY_PATH = IMG_DIR / "enemy"

PLAYER_IDLE_PATH = PLAYER_PATH / "Idle"
PLAYER_RUN_PATH = PLAYER_PATH / "Run"
PLAYER_JUMP_PATH = PLAYER_PATH / "Jump"
PLAYER_DEATH_PATH = PLAYER_PATH / "Death"

ENEMY_IDLE_PATH = ENEMY_PATH / "Idle"
ENEMY_RUN_PATH = ENEMY_PATH / "Run"
ENEMY_JUMP_PATH = ENEMY_PATH / "Jump"
ENEMY_DEATH_PATH = ENEMY_PATH / "Death"

ICON_PATH = IMG_DIR / "icons"
EXPLOSION_PATH = IMG_DIR / "explosion"

GRAVITY = 1
FPS = 60

BG = (144, 201, 120)
BLACK = (0, 0, 0)

SCREEN_WIDTH = 800
SCREEN_HEIGHT = int(0.8 * SCREEN_WIDTH)

INITIAL_BULLETS = 20
INITIAL_GRENADES = 5

GROUND = 400
SPEED = 10
BULLET_SPEED = 5
GRENADE_SPEED = 8

BULLET_DAMAGE = 25
GRENADE_DAMAGE = 100

BULLETS_GIVEN = 10
GRENADES_GIVEN = 1
HEALTH_GIVEN = 50

PLAYER_START_X = 200
PLAYER_START_Y = GROUND
PLAYER_SCALE = 2.5
